# Generated by Django 5.2.8 on 2025-12-02 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='planets/')),
                ('description', models.TextField()),
                ('distance_from_sun', models.CharField(blank=True, max_length=100)),
                ('radius', models.CharField(blank=True, max_length=100)),
                ('gravity', models.CharField(blank=True, max_length=100)),
                ('day_length', models.CharField(blank=True, max_length=100)),
                ('atmosphere', models.CharField(blank=True, max_length=200)),
                ('temperature', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('terrestrial', 'Terrestrial'), ('gas_giant', 'Gas Giant'), ('ice_giant', 'Ice Giant'), ('dwarf', 'Dwarf Planet')], default='terrestrial', max_length=20)),
                ('moons_count', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planets.planet')),
            ],
        ),
    ]
